### ISSUE TITLE
`./gen-git-build.sh` will make Git tree dirty now

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#40] opened 2022-09-07 13:43 UTC
We have to consider how on-repository `saved/psyntax.scm` and `psyntax-prefix.txt` treated. Delete it if okay, save it another branch or directory if we need them absolutely.

```
okuoku@prism mosh % git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   boot/runtimes/psyntax-mosh/psyntax-prefix.txt
	modified:   boot/runtimes/psyntax-mosh/saved/psyntax.scm
```

**Comment by higepon** [comment] 2022-09-07 22:14
In short I think keep it as it.

## Background
- (A) Many years ago we needed to save stable (= working) psyntax.scm somewhere. Because it's easily broken in developers env and we may have lost ability to bootstrap.
- (B) Now we have a stable way of bootstraping mosh.git head in docker or GitHub Actions. So it's not critical any more.

## Why we keep it?
- Well I'm not sure if these infra will exists in the long run.
- It's still convenient to keep them in the repo

## What developers to do?
Just commit the file in the branch when it's working as expected.

Please let me know what you think.

**Comment by higepon** [comment] 2022-09-08 13:28
I see your point.
Let's not store them in git repository then?

**Comment by okuoku** [comment] 2022-09-08 14:12
Since now we always do bootstrap on GitHub Actions, there is no point keep it on-repository I think.

**Comment by higepon** [comment] 2022-09-08 22:19
This has been fixed in https://github.com/higepon/mosh/pull/46.

**Comment by okuoku** [comment] 2022-09-09 13:14
How about `psyntax-prefix.txt` ? Is this wanted to keep it being matched (ie. If we see diff on `psyntax-prefix.txt`, we have used wrong version of Mosh to bootstrap)?

```diff
diff --git a/boot/runtimes/psyntax-mosh/psyntax-prefix.txt b/boot/runtimes/psyntax-mosh/psyntax-prefix.txt
index 8c7e5a66..7371f47a 100644
--- a/boot/runtimes/psyntax-mosh/psyntax-prefix.txt
+++ b/boot/runtimes/psyntax-mosh/psyntax-prefix.txt
@@ -1 +1 @@
-A
\ No newline at end of file
+B
\ No newline at end of file
```

**Comment by okuoku** [comment] 2022-09-09 16:52
Uh, it seems we need that file...

<img width="857" alt="image" src="https://user-images.githubusercontent.com/100813/189401159-3a63d418-1758-49c0-9887-a14bacb9c449.png">

Perhaps we should install it along with `mosh` executable and copy it on bootstrap..?

**Comment by higepon** [comment] 2022-09-09 23:15
Thanks for the catch! I over looked it. I think the make target should have failed instead of ignoring it.

**Comment by higepon** [comment] 2022-09-09 23:53
## WIP: Investigation notes 

### The reason why we need gensym prefix
https://github.com/higepon/mosh/blob/master/Makefile.am#L383
```sh
#   (b) When we precompile system libraries, we want to control the start index of gensym.
#       Since we should avoid index overlapping between pre-compile libraries and pre-compiled psyntax.
#       So using environment variable MOSH_GENSYM_PREFIX, we control the prefix.
```

This makes sense.

### Where MOSH_GENSYM_PREFIX is actually set
https://github.com/higepon/mosh/blob/master/boot/runtimes/psyntax-mosh/Makefile#L15
```
psyntax.scm: $(PSYNTAX_SOURCES)
	MOSH_GENSYM_PREFIX=`$(MOSH) print-prefix.ss` $(MOSH) psyntax-buildscript-mosh.ss
```

I believe ```MOSH_GENSYM_PREFIX``` can only be seen in ```psyntax-buildscript-mosh.ss```.  ```psyntax-buildscript-mosh.ss``` is calling ```(gensym)``` as it goes.

So I would assume ```(gensym)``` is using ```MOSH_GENSYM_PREFIX```.


```(gensym)``` is implemented in the backend.
```c++
Object scheme::gensymEx(VM* theVM, int argc, const Object* argv)
```

And it is using
```c++
static const char* gensymPrefix = "a";
```

It can be changed by ```(gensym-prefix-set! ...)```
```c++
Object scheme::gensymPrefixSetDEx(VM* theVM, int argc, const Object* argv)
{
    DeclareProcedureName("gensym-prefix-set!");
    checkArgumentLength(1);
    argumentAsSymbol(0, prefix);
    gensymPrefix = ucs4string(prefix->c_str()).ascii_c_str();
    return Object::Undef;
}
```

But I don't see ```(gensym-prefix-set! ...)``` used for the purpose except for the following which I believe unrelated.
```scheme
              (when (mosh-cache-dir)
                (gensym-prefix-set! (prefix-inc! (string-append (mosh-cache-dir) "/prefix.txt"))))
```

Let's confirm gensym-prefix-set! is not used as expected. I put ```(display (gensym))``` in ```psyntax-buildscript-mosh.ss``` and I got ```gR5a3e``` even though I put ```X``` in the prefix text.

### What is the problem here?
- During the bootstrap process different call of ```mosh``` can generate exact same symbol.
- psyntax bootstrap is not setting ```gensym-prefix-set!```.

### Question
I do understand the necessity of gensym prefix for psyntax generation. I believe it's there to prevent symbol collision with other bootstrap process + future ```(gen-sym)``` call in the binary. In that case can't we just say we'd use prefix ```p``` for psyntax? Then we don't need the prefix text or save the next-ch in the script.

**Comment by higepon** [comment] 2022-09-09 23:59
When caching libraries we're using ```gensym-prefix-set!``` properly.
```
cat .mosh/prefix.txt 
```

**Comment by higepon** [comment] 2022-09-10 00:06
@okuoku Any thoughts? Do you remeber any of these?

My current plan is to use and reserve ```P``` prefix for psyntax expander.

**Comment by okuoku** [comment] 2022-09-10 00:18
I don't remember either but how about ACC(auto compilation cache) intervention? The build process already contain `--disable-acc` but I'm not sure why; didn't that (another) workaround for the conflict?

**Comment by higepon** [comment] 2022-09-10 00:24
Very good point.
I think acc is using gensym-set-prefix! properly. The prefix starts from 'a' and I see it's g in the other prefix.txt for ACC.

```but I'm not sure why; didn't that (another) workaround for the conflict?```

I don't remember either. But could be.
Let me go ahead with ```P``` prefix approach for psyntax and see if it works.

Now I'm guessing that nmosh expander issue we saw for ffi-open was caused by something similar to this.
You may want to check.

**Comment by higepon** [comment] 2022-09-10 01:11
The fix is on the way.
https://github.com/higepon/mosh/pull/59

**Closed** 2022-09-10 01:21 UTC
